messages:
  prefix: "&7[&bBedrockMiner&7] &e"
  not-bedrock: "&eWarning! You can only break &6Bedrock &eusing this pickaxe"
  no-permission:
    craft:
      pickaxe: "&cYou do not have permission to craft a &6Bedrock Pickaxe&e."
      bedrock: "&cYou do not have permission to craft &6Bedrock&e."
    use:
      pickaxe: "&cYou do not have permission to use a &6Bedrock Pickaxe&e."
      bedrock: "&cYou do not have permission to place &6Bedrock&e."
    command:
      give: "&eYou do not have permission to use that command."
      console: "&cYou must be a player to utilize these commands!"
      invalid: "&cThat command is invalid."
    breakbottom: "&eYou can not break the bottom bedrock block."

#If disabled, disallows players to break the bottom bedrock block (Y=0)
breakbottom: true
#If enabled, drops bedrock blocks if the pickaxe used if enchanted with silk touch
silktouch: true
#The amount of durability to remove from the pickaxe on each usage
durability: 10