name: BedrockMiner
version: 2.0.0
main: com.adrianwowk.bedrockminer.BedrockMiner
author: Adrian Wowk
commands:
  bedrockminer:
    usage: /<command> give
    aliases: bm
api-version: 1.14
permissions:
  bedrockminer.use:
    description: Allows use of bedrock pickaxe
    default: op
  bedrockminer.place:
    description: Allows placing of bedrock
    default: op
  bedrockminer.give:
    description: Allows use of /bm give command
    default: op
  bedrockminer.craft.pickaxe:
    description: Allows crafting of a bedrock pickaxe
    default: op
  bedrockminer.craft.bedrock:
    description: Allows crafting of bedrock
    default: op
  bedrockminer.craft:
      description: Allows crafting of custom items
      default: op
      children:
        bedrockminer.craft.bedrock: true
        bedrockminer.craft.pickaxe: true
  bedrockminer.reload:
    default: op
  bedrockminer.*:
    description: Wildcard permission
    default: op
    children:
      bedrockminer.use: true
      bedrockminer.give: true
      bedrockminer.craft.pickaxe: true
      bedrockminer.craft.bedrock: true